import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="white">
			<body className={inter.className}>
				<Providers>
					<header className="flex bg-gray-100 justify-between px-8 py-4">
						<div>
							<Link href="/">
								<img className="w-20" src="/allegra-store-logo.jpg" alt="" />
							</Link>
						</div>
						<div>
							<nav>
								<Link href="/create-order">
									<button
										className="my-4
									 w-full
									 bg-indigo-500z-0
									 group
									 relative
									 inline-flex
									 items-center
									 justify-center
									 box-border
									 appearance-none
									 select-none
									 whitespace-nowrap
									 font-normal
									 subpixel-antialiased
									 overflow-hidden
									 tap-highlight-transparent
									 outline-none
									 data-[focus-visible=true]:z-10
									 data-[focus-visible=true]:outline-2
									 data-[focus-visible=true]:outline-focus
									 data-[focus-visible=true]:outline-offset-2
									 px-unit-4
									 min-w-unit-20
									 h-unit-10
									 text-small
									 gap-unit-2
									 rounded-medium
									 [&>svg]:max-w-[theme(spacing.unit-8)]
									 data-[pressed=true]:scale-[0.97]
									 transition-transform-colors
									 motion-reduce:transition-none
									 text-primary-foreground
									 bg-indigo-500">
										Crear órden
									</button>
								</Link>
							</nav>
						</div>
					</header>
					<div className="px-8 mb-28">{children}</div>
				</Providers>
			</body>
		</html>
	);
}
